-- Find total customers by countries
SELECT 
country,
COUNT(customer_key) as Total_Customers
FROM gold.dim_customers
GROUP BY country
ORDER BY Total_Customers DESC;


-- Find total customers by gender
SELECT 
gender,
COUNT(customer_key) as Total_Customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY Total_Customers DESC;


-- Find total products by category
SELECT
category,
COUNT(product_key) as Total_Products
FROM gold.dim_products
GROUP BY CATEGORY
ORDER BY Total_Products DESC;


-- What is the average costs in each category ?
SELECT
category,
AVG(cost) as Avg_Cost
FROM gold.dim_products
GROUP BY CATEGORY
ORDER BY Avg_Cost DESC;


-- What is the total revenue generated for each category ?
SELECT 
p.category,
SUM(f.sales_amount) Total_Revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY Total_Revenue DESC;

-- Find total revenue that is generated by each customer
SELECT
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS Total_Revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY 
c.customer_key,
c.first_name,
c.last_name
ORDER BY Total_Revenue DESC;

-- What is the distribution of sold items across countries ?
SELECT
c.country,
SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY 
c.country
ORDER BY total_sold_items DESC;
